/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResultsScanIdRouteImport } from './routes/results.$scanId'
import { Route as ScanDeepfakeRouteImport } from './routes/scan.deepfake'
import { Route as ScanJobOfferRouteImport } from './routes/scan.job-offer'
import { Route as ScanScreenshotRouteImport } from './routes/scan.screenshot'
import { Route as ScanUrlRouteImport } from './routes/scan.url'
import { Route as ScanVoiceRouteImport } from './routes/scan.voice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsScanIdRoute = ResultsScanIdRouteImport.update({
  id: '/results/$scanId',
  path: '/results/$scanId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanDeepfakeRoute = ScanDeepfakeRouteImport.update({
  id: '/scan/deepfake',
  path: '/scan/deepfake',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanJobOfferRoute = ScanJobOfferRouteImport.update({
  id: '/scan/job-offer',
  path: '/scan/job-offer',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanScreenshotRoute = ScanScreenshotRouteImport.update({
  id: '/scan/screenshot',
  path: '/scan/screenshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanUrlRoute = ScanUrlRouteImport.update({
  id: '/scan/url',
  path: '/scan/url',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanVoiceRoute = ScanVoiceRouteImport.update({
  id: '/scan/voice',
  path: '/scan/voice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/results/$scanId': typeof ResultsScanIdRoute
  '/scan/deepfake': typeof ScanDeepfakeRoute
  '/scan/job-offer': typeof ScanJobOfferRoute
  '/scan/screenshot': typeof ScanScreenshotRoute
  '/scan/url': typeof ScanUrlRoute
  '/scan/voice': typeof ScanVoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/results/$scanId': typeof ResultsScanIdRoute
  '/scan/deepfake': typeof ScanDeepfakeRoute
  '/scan/job-offer': typeof ScanJobOfferRoute
  '/scan/screenshot': typeof ScanScreenshotRoute
  '/scan/url': typeof ScanUrlRoute
  '/scan/voice': typeof ScanVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/results/$scanId': typeof ResultsScanIdRoute
  '/scan/deepfake': typeof ScanDeepfakeRoute
  '/scan/job-offer': typeof ScanJobOfferRoute
  '/scan/screenshot': typeof ScanScreenshotRoute
  '/scan/url': typeof ScanUrlRoute
  '/scan/voice': typeof ScanVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/profile'
    | '/register'
    | '/results/$scanId'
    | '/scan/deepfake'
    | '/scan/job-offer'
    | '/scan/screenshot'
    | '/scan/url'
    | '/scan/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/profile'
    | '/register'
    | '/results/$scanId'
    | '/scan/deepfake'
    | '/scan/job-offer'
    | '/scan/screenshot'
    | '/scan/url'
    | '/scan/voice'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/profile'
    | '/register'
    | '/results/$scanId'
    | '/scan/deepfake'
    | '/scan/job-offer'
    | '/scan/screenshot'
    | '/scan/url'
    | '/scan/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResultsScanIdRoute: typeof ResultsScanIdRoute
  ScanDeepfakeRoute: typeof ScanDeepfakeRoute
  ScanJobOfferRoute: typeof ScanJobOfferRoute
  ScanScreenshotRoute: typeof ScanScreenshotRoute
  ScanUrlRoute: typeof ScanUrlRoute
  ScanVoiceRoute: typeof ScanVoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$scanId': {
      id: '/results/$scanId'
      path: '/results/$scanId'
      fullPath: '/results/$scanId'
      preLoaderRoute: typeof ResultsScanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/deepfake': {
      id: '/scan/deepfake'
      path: '/scan/deepfake'
      fullPath: '/scan/deepfake'
      preLoaderRoute: typeof ScanDeepfakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/job-offer': {
      id: '/scan/job-offer'
      path: '/scan/job-offer'
      fullPath: '/scan/job-offer'
      preLoaderRoute: typeof ScanJobOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/screenshot': {
      id: '/scan/screenshot'
      path: '/scan/screenshot'
      fullPath: '/scan/screenshot'
      preLoaderRoute: typeof ScanScreenshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/url': {
      id: '/scan/url'
      path: '/scan/url'
      fullPath: '/scan/url'
      preLoaderRoute: typeof ScanUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/voice': {
      id: '/scan/voice'
      path: '/scan/voice'
      fullPath: '/scan/voice'
      preLoaderRoute: typeof ScanVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResultsScanIdRoute: ResultsScanIdRoute,
  ScanDeepfakeRoute: ScanDeepfakeRoute,
  ScanJobOfferRoute: ScanJobOfferRoute,
  ScanScreenshotRoute: ScanScreenshotRoute,
  ScanUrlRoute: ScanUrlRoute,
  ScanVoiceRoute: ScanVoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
